-Wsign-compare
Due to comparison between integers of type int (signed) and size_t (unsigned) GCC (at least version 5.1.1) with -Wsign-compare and -Werror enabled emits the following:

include/base64.h: In static member function ‘static bool Base64::Encode(const char*, int, char*, int)’:
include/base64.h:63:20: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     if (out_length < encoded_length) return false;
                    ^
include/base64.h: In static member function ‘static bool Base64::Decode(const char*, int, char*, int)’:
include/base64.h:156:20: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     if (out_length < decoded_length) return false;

and fails to build any source file including base64.h.

Added static_casts from int to unsigned on the left hand side of the offending comparisons to ameliorate this.  Ideally out_length would be of type size_t but this would require an API change as out_length is a parameter.